const DEFAULT_PRODUCTS=[
 {id:1,name:'Bot WhatsApp Premium',price:150000,category:'Bot WhatsApp',stock:'Ready',image:'https://images.unsplash.com/photo-1611605698335-8b1569810432?auto=format&fit=crop&w=900&q=85',description:'Bot WhatsApp praktis untuk membantu otomasi bisnis, layanan pelanggan, dan kebutuhan operasional Anda.'},
 {id:2,name:'Website Landing Page',price:350000,category:'Website',stock:'Ready',image:'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=85',description:'Landing page modern yang cepat, responsif, dan siap digunakan untuk memperkenalkan bisnis Anda.'},
 {id:3,name:'Paket Desain Sosial Media',price:125000,category:'Desain',stock:'Ready',image:'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=85',description:'Kumpulan desain premium untuk membuat tampilan sosial media bisnis lebih konsisten dan profesional.'}
];
const DEFAULT_PAYMENTS=[{id:1,name:'DANA',number:'085177961224',qr:''},{id:2,name:'GoPay',number:'085789963681',qr:''}];
const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const get=(key,fallback)=>JSON.parse(localStorage.getItem(key)||'null')||fallback;
let products=get('xyrozProducts',DEFAULT_PRODUCTS), payments=get('xyrozPayments',DEFAULT_PAYMENTS), selected=null;
const by=id=>document.getElementById(id), save=()=>{localStorage.setItem('xyrozProducts',JSON.stringify(products));localStorage.setItem('xyrozPayments',JSON.stringify(payments));};
function renderProducts(){const grid=by('productGrid');if(!grid)return;const q=(by('searchInput')?.value||'').toLowerCase(),cat=by('categoryFilter')?.value||'all';const list=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q)&&(cat==='all'||p.category===cat));grid.innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-image" style="background-image:url('${p.image}')"><span>${p.stock}</span></div><div class="product-info"><small>${p.category}</small><h3>${p.name}</h3><strong>${money(p.price)}</strong><button class="secondary-btn" onclick="selectProduct(${p.id})">Lihat detail →</button></div></article>`).join(''):'<div class="empty-state">Produk tidak ditemukan.</div>';}
function selectProduct(id){selected=products.find(p=>p.id===id);if(!selected)return;by('detailCategory').textContent=selected.category;by('detailName').textContent=selected.name;by('detailPrice').textContent=money(selected.price);by('detailDescription').textContent=selected.description;by('detailStock').textContent=selected.stock;by('detailImage').style.backgroundImage=`url('${selected.image}')`;by('selectedProductDisplay').value=selected.name;by('orderProductName').value=selected.name;by('orderProductPrice').value=money(selected.price);by('paymentProductName').textContent=selected.name;by('paymentProductPrice').textContent=money(selected.price);by('paymentEmpty').classList.add('hidden');by('paymentDetails').classList.remove('hidden');renderPayments();by('checkout').scrollIntoView({behavior:'smooth'});}
function renderPayments(){const wrap=by('paymentMethods');if(!wrap)return;wrap.innerHTML=payments.map(p=>`<div class="payment-method"><div><small>${p.name}</small><strong>${p.number||'Scan QR untuk membayar'}</strong></div>${p.qr?`<img src="${p.qr}" alt="QR ${p.name}">`:'<div class="qr-placeholder">QR</div>'}</div>`).join('');}
function setupStore(){if(!by('productGrid'))return;const cats=[...new Set(products.map(p=>p.category))];by('categoryFilter').innerHTML='<option value="all">Semua kategori</option>'+cats.map(c=>`<option>${c}</option>`).join('');renderProducts();by('searchInput').oninput=renderProducts;by('categoryFilter').onchange=renderProducts;by('selectProductBtn').onclick=()=>selected&&selectProduct(selected.id);by('orderForm').onsubmit=e=>{e.preventDefault();if(!selected){alert('Silakan pilih produk terlebih dahulu.');return}const msg=`Halo Xyroz, saya ingin membeli:%0A%0AProduk: ${selected.name}%0AHarga: ${money(selected.price)}%0ANama: ${by('customerName').value}%0ANomor WhatsApp: ${by('customerPhone').value}%0ACatatan: ${by('customerNote').value||'-'}%0A%0ASaya akan mengirim bukti pembayaran di sini.`;window.location.href=`https://wa.me/6285177356154?text=${msg}`;};}
function resetForm(){['productId','productName','productPrice','productCategory','productImage','productDescription'].forEach(id=>{if(by(id))by(id).value=''});by('productStock').value='Ready';by('formTitle').textContent='Tambah produk';by('cancelEditBtn').classList.add('hidden');}
function renderOwner(){const list=by('ownerProductList');if(!list)return;by('totalProducts').textContent=products.length;by('totalCategories').textContent=new Set(products.map(p=>p.category)).size;list.innerHTML=products.map(p=>`<tr><td><strong>${p.name}</strong></td><td>${p.category}</td><td>${money(p.price)}</td><td><button class="table-btn" onclick="editProduct(${p.id})">Edit</button><button class="table-btn danger" onclick="deleteProduct(${p.id})">Hapus</button></td></tr>`).join('');const pay=by('paymentOwnerList');pay.innerHTML=payments.map(p=>`<div class="owner-payment"><span><strong>${p.name}</strong> ${p.number||'(QR only)'}</span><button class="table-btn danger" onclick="deletePayment(${p.id})">Hapus</button></div>`).join('');}
function readImage(file){return new Promise((resolve,reject)=>{if(!file){resolve('');return}const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});}
function setupQrPicker(){const input=by('paymentQrFile'),box=by('qrUploadBox'),preview=by('qrPreview');if(!input)return;input.onchange=()=>{const file=input.files[0];if(!file)return;if(file.size>3*1024*1024){alert('Ukuran foto QR maksimal 3 MB.');input.value='';return}const reader=new FileReader();reader.onload=()=>{preview.src=reader.result;box.classList.add('has-image')};reader.readAsDataURL(file);};}
function clearQrPicker(){const input=by('paymentQrFile'),box=by('qrUploadBox'),preview=by('qrPreview');if(input)input.value='';if(preview)preview.removeAttribute('src');if(box)box.classList.remove('has-image');}
function setupOwner(){if(!by('loginForm'))return;setupQrPicker();by('loginForm').onsubmit=e=>{e.preventDefault();if(by('ownerPassword').value!=='xyroz2026'){alert('Password salah.');return}by('loginPanel').classList.add('hidden');by('ownerDashboard').classList.remove('hidden');renderOwner()};by('productForm').onsubmit=e=>{e.preventDefault();const id=Number(by('productId').value);const item={id:id||Date.now(),name:by('productName').value,price:Number(by('productPrice').value),category:by('productCategory').value,stock:by('productStock').value,image:by('productImage').value,description:by('productDescription').value};products=id?products.map(p=>p.id===id?item:p):[...products,item];save();resetForm();renderOwner();alert('Produk berhasil disimpan.')};by('cancelEditBtn').onclick=resetForm;by('paymentForm').onsubmit=async e=>{e.preventDefault();const file=by('paymentQrFile').files[0];if(file&&file.size>3*1024*1024){alert('Ukuran foto QR maksimal 3 MB.');return}const qr=await readImage(file);payments.push({id:Date.now(),name:by('paymentName').value,number:by('paymentNumber').value,qr});save();e.target.reset();clearQrPicker();renderOwner();alert('Metode pembayaran dan foto QR berhasil ditambahkan.')};}
window.selectProduct=selectProduct;window.deleteProduct=id=>{if(confirm('Hapus produk ini?')){products=products.filter(p=>p.id!==id);save();renderOwner()}};window.editProduct=id=>{const p=products.find(x=>x.id===id);['productId','productName','productPrice','productCategory','productStock','productImage','productDescription'].forEach((k,i)=>by(k).value=[p.id,p.name,p.price,p.category,p.stock,p.image,p.description][i]);by('formTitle').textContent='Edit produk';by('cancelEditBtn').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})};window.deletePayment=id=>{if(confirm('Hapus metode ini?')){payments=payments.filter(p=>p.id!==id);save();renderOwner()}};
setupStore();setupOwner();
