const defaults=[{id:1,name:'Bot WhatsApp Premium',price:150000,category:'Bot WhatsApp',stock:'Ready',image:'https://images.unsplash.com/photo-1611605698335-8b1569810432?auto=format&fit=crop&w=900&q=80',desc:'Bot WhatsApp siap pakai untuk membantu operasional bisnis Anda.'},{id:2,name:'Website Landing Page',price:250000,category:'Website',stock:'Ready',image:'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=900&q=80',desc:'Landing page modern, cepat, dan cocok untuk promosi produk.'},{id:3,name:'Paket Desain Konten',price:100000,category:'Desain',stock:'Ready',image:'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&w=900&q=80',desc:'Paket desain konten profesional untuk kebutuhan media sosial.'}];
const money=n=>'Rp '+Number(n).toLocaleString('id-ID');let products=JSON.parse(localStorage.getItem('xyrozProducts')||'null')||defaults;let selected=null;
function by(id){return document.getElementById(id)}
function renderProducts(){const grid=by('productGrid');if(!grid)return;const q=(by('searchInput')?.value||'').toLowerCase(),cat=by('categoryFilter')?.value||'all';grid.innerHTML=products.filter(p=>(p.name+p.category).toLowerCase().includes(q)&&(cat==='all'||p.category===cat)).map(p=>`<article class="product-card"><img src="${p.image}" alt="${p.name}"><div class="product-info"><span class="eyebrow muted">${p.category}</span><h3>${p.name}</h3><p>${p.desc}</p><strong class="price">${money(p.price)}</strong><button class="primary-btn choose-product" data-id="${p.id}" type="button">Lihat & Pilih</button></div></article>`).join('')||'<p>Produk tidak ditemukan.</p>';document.querySelectorAll('.choose-product').forEach(b=>b.onclick=()=>selectProduct(Number(b.dataset.id)))}
function selectProduct(id){selected=products.find(p=>p.id===id);if(!selected)return;by('detailCategory').textContent=selected.category;by('detailName').textContent=selected.name;by('detailPrice').textContent=money(selected.price);by('detailDescription').textContent=selected.desc;by('detailStock').textContent=selected.stock;by('detailImage').style.backgroundImage=`url("${selected.image}")`;by('selectedProductDisplay').value=selected.name+' — '+money(selected.price);by('orderProductName').value=selected.name;by('orderProductPrice').value=money(selected.price);by('paymentProductName').textContent=selected.name;by('paymentProductPrice').textContent=money(selected.price);by('paymentEmpty').classList.add('hidden');by('paymentDetails').classList.remove('hidden');by('checkout').scrollIntoView({behavior:'smooth'});}
function setupStore(){if(!by('productGrid'))return;const cats=[...new Set(products.map(p=>p.category))];by('categoryFilter').innerHTML='<option value="all">Semua Kategori</option>'+cats.map(c=>`<option>${c}</option>`).join('');renderProducts();by('searchInput').oninput=renderProducts;by('categoryFilter').onchange=renderProducts;by('selectProductBtn').onclick=()=>selected&&selectProduct(selected.id);document.querySelectorAll('.copy-btn').forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(b.dataset.copy);const old=b.textContent;b.textContent='Tersalin ✓';setTimeout(()=>b.textContent=old,1500)});}
function setupOwner(){const login=by('loginForm');if(!login)return;login.onsubmit=e=>{e.preventDefault();if(by('ownerPassword').value==='xyroz2026'){by('loginPanel').classList.add('hidden');by('ownerDashboard').classList.remove('hidden');renderOwner()}else alert('Password salah.')};by('logoutBtn')?.addEventListener('click',()=>location.reload());}
function renderOwner(){const list=by('ownerProductList');if(!list)return;by('totalProducts').textContent=products.length;by('totalCategories').textContent=new Set(products.map(p=>p.category)).size;list.innerHTML=products.map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="secondary-btn" onclick="editProduct(${p.id})">Edit</button><button class="secondary-btn" onclick="deleteProduct(${p.id})">Hapus</button></td></tr>`).join('')}
window.deleteProduct=id=>{products=products.filter(p=>p.id!==id);localStorage.setItem('xyrozProducts',JSON.stringify(products));renderOwner()};window.editProduct=id=>alert('Silakan gunakan form produk untuk mengedit.');setupStore();setupOwner();
